version: '3.8'

services:
  api:
    image: dimzaridis/simplatab-machine-learning-automator:0.7.7-TestVersion
    ports:
      - "5000:5000"
    volumes:
      - ${INPUT_FOLDER}:/input_data
      - ${OUTPUT_FOLDER}:/Materials